settings:
  height: 3000
  width: 3000
  bg-color: d14a2d

planets:
  # meteosat-11:
  #   x: 10
  #   y: 20
  #   width: 300
  #   height: 300

  # goes-16:
  #   x: 30
  #   y: 40
  #   width: 300
  #   height: 300

  sentinel:
    x: 300
    y: 400
    width: 300
    height: 300
    scale: 2
    latitude: 22
    longitude: 9
  
  sdo:
    x: 1
    y: 1
    width: 200
    height: 200
    bandwidth: "0304"