settings:
  height: 1200
  width: 1200
  bg-color: d14a2d

planets:
  # meteosat-11:
  #   x: 0
  #   y: 0
  #   width: 1000
  #   height: 1000
  #   color: geocolor

  # goes-16:
  #   x: 500
  #   y: 0
  #   width: 500
  #   height: 500
  #   color: natural_color

  # sentinel:
  #   x: 300
  #   y: 400
  #   width: 600
  #   height: 400
  #   scale: 200
  #   latitude: 53
  #   longitude: 9
  
  sdo:
    x: 1
    y: 1
    width: 100
    height: 100
    bandwidth: "0304"